# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

target 'FantasyBasketball' do
    pod 'MZAppearance'
    pod 'RESideMenu', '~> 4.0.7'
end

target 'FantasyBasketballTests' do

end

