# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'FantasyBasketball' do
    pod 'RESideMenu'
    pod 'ZFDragableModalTransition'
    pod 'JBChartView'
    pod 'GraphKit'
end

target 'FantasyBasketballTests' do

end

